#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${RMID_DB_USER} WITH ENCRYPTED PASSWORD '${RMID_DB_PASSWORD}';
    CREATE DATABASE ${RMID_DB_NAME};
    GRANT ALL PRIVILEGES ON DATABASE ${RMID_DB_NAME} TO ${RMID_DB_USER};
    CREATE USER ${AUTOMODELER_DB_USER} WITH ENCRYPTED PASSWORD '${AUTOMODELER_DB_PASSWORD}';
    CREATE DATABASE ${AUTOMODELER_DB_NAME};
    GRANT ALL PRIVILEGES ON DATABASE ${AUTOMODELER_DB_NAME} TO ${AUTOMODELER_DB_USER};
EOSQL
